export const freedomBadges = [
  {
    id: "gandhi_first_step",
    nameEn: "Mahatma Gandhi – First Step Badge",
    nameHi: "महात्मा गांधी – पहला कदम बैज",
    virtueEn: "First Step & Truth",
    virtueHi: "पहला कदम और सत्य",
    icon: "🌟",
    freedomFighter: "Mahatma Gandhi",
    quoteEn: "Be the change that you wish to see in the world.",
    quoteHi: "खुद वो बदलाव बनिए जो आप दुनिया में देखना चाहते हैं।",
    requirementEn: "Complete your 1st task",
    requirementHi: "अपना पहला कार्य पूरा करें",
    type: "task_count",
    threshold: 1
  },
  {
    id: "bhagat_singh_courage",
    nameEn: "Bhagat Singh – Courage Badge",
    nameHi: "भगत सिंह – साहस बैज",
    virtueEn: "Fearless Courage",
    virtueHi: "निडर साहस",
    icon: "🔥",
    freedomFighter: "Bhagat Singh",
    quoteEn: "They may kill me, but they cannot kill my ideas.",
    quoteHi: "वे मुझे मार सकते हैं, लेकिन मेरे विचारों को नहीं मार सकते।",
    requirementEn: "Complete 5 tasks",
    requirementHi: "5 कार्य पूरे करें",
    type: "task_count",
    threshold: 5
  },
  {
    id: "sardar_patel_discipline",
    nameEn: "Sardar Patel – Discipline Badge",
    nameHi: "सरदार पटेल – अनुशासन बैज",
    virtueEn: "Iron Discipline & Unity",
    virtueHi: "लोह अनुशासन और एकता",
    icon: "🦚",
    freedomFighter: "Sardar Vallabhbhai Patel",
    quoteEn: "Manpower without unity is not a strength unless it is harmonized.",
    quoteHi: "एकता के बिना जनशक्ति कोई शक्ति नहीं है जब तक कि इसे सही रूप में संगठित न किया जाए।",
    requirementEn: "Complete all daily tasks in a day",
    requirementHi: "एक दिन के सभी कार्य पूरे करें",
    type: "daily_complete",
    threshold: 1
  },
  {
    id: "laksmi_determination",
    nameEn: "Rani Lakshmibai – Determination Badge",
    nameHi: "रानी लक्ष्मीबाई – संकल्प बैज",
    virtueEn: "Unshakable Determination",
    virtueHi: "अडिग संकल्प",
    icon: "✨",
    freedomFighter: "Rani Lakshmibai",
    quoteEn: "We will fight for freedom until our last breath.",
    quoteHi: "हम अपनी आखिरी सांस तक आजादी के लिए लड़ेंगे।",
    requirementEn: "Maintain a 3-day streak",
    requirementHi: "3 दिनों की स्ट्रिक बनाए रखें",
    type: "streak",
    threshold: 3
  },
  {
    id: "subhas_leadership",
    nameEn: "Subhas Chandra Bose – Leadership Badge",
    nameHi: "सुभाष चंद्र बोस – नेतृत्व बैज",
    virtueEn: "Visionary Leadership",
    virtueHi: "दूरदर्शी नेतृत्व",
    icon: "🛡️",
    freedomFighter: "Netaji Subhas Chandra Bose",
    quoteEn: "Give me blood and I will give you freedom!",
    quoteHi: "तुम मुझे खून दो, मैं तुम्हें आजादी दूंगा!",
    requirementEn: "Maintain a 7-day streak",
    requirementHi: "7 दिनों की स्ट्रिक बनाए रखें",
    type: "streak",
    threshold: 7
  },
  {
    id: "ambedkar_knowledge",
    nameEn: "Dr. B. R. Ambedkar – Knowledge Badge",
    nameHi: "डॉ. बी. आर. अम्बेडकर – ज्ञान बैज",
    virtueEn: "Wisdom & Equality",
    virtueHi: "ज्ञान और समानता",
    icon: "📚",
    freedomFighter: "Dr. B. R. Ambedkar",
    quoteEn: "Educate, Agitate, Organize.",
    quoteHi: "शिक्षित बनो, संघर्ष करो, संगठित रहो।",
    requirementEn: "Maintain a 15-day streak",
    requirementHi: "15 दिनों की स्ट्रिक बनाए रखें",
    type: "streak",
    threshold: 15
  },
  {
    id: "azad_bravery",
    nameEn: "Chandrashekhar Azad – Bravery Badge",
    nameHi: "चंद्रशेखर आजाद – वीरता बैज",
    virtueEn: "Indomitable Valor",
    virtueHi: "अदम्य वीरता",
    icon: "🏆",
    freedomFighter: "Chandrashekhar Azad",
    quoteEn: "Dushman ki goliyon ka hum samna karenge, Azad hi rahe hain, azad hi rahenge!",
    quoteHi: "दुश्मन की गोलियों का हम सामना करेंगे, आजाद ही रहे हैं, आजाद ही रहेंगे!",
    requirementEn: "Complete 15-day milestone",
    requirementHi: "15 दिन का मील का पत्थर पूरा करें",
    type: "streak",
    threshold: 15
  },
  {
    id: "gandhi_gold",
    nameEn: "Gandhi Ji Gold Badge",
    nameHi: "गांधी जी गोल्ड बैज",
    virtueEn: "Mastery of Truth & Perseverance",
    virtueHi: "सत्य और दृढ़ता की महारत",
    icon: "👑",
    freedomFighter: "Mahatma Gandhi Gold",
    quoteEn: "Strength does not come from physical capacity. It comes from an indomitable will.",
    quoteHi: "ताकत शारीरिक क्षमता से नहीं आती। यह अदम्य इच्छाशक्ति से आती है।",
    requirementEn: "Maintain a 30-day streak",
    requirementHi: "30 दिनों की स्ट्रिक बनाए रखें",
    type: "streak",
    threshold: 30
  },
  {
    id: "bharat_ratna",
    nameEn: "Bharat Ratna Productivity Badge",
    nameHi: "भारत रत्न उत्पादकता बैज",
    virtueEn: "National Productivity Excellence",
    virtueHi: "राष्ट्रीय उत्पादकता उत्कृष्टता",
    icon: "",
    iconComponent: "WorkspacePremium",
    freedomFighter: "Bharat Ratna Honor",
    quoteEn: "Pledge towards excellence in every endeavor for the nation and its duty.",
    quoteHi: "मातृभूमि भारत के लिए हर प्रयास में उत्कृष्टता का संकल्प।",
    requirementEn: "Complete 30-day streak & 50 total tasks",
    requirementHi: "30 दिन की स्ट्रिक और 50 कुल कार्य पूरे करें",
    type: "streak",
    threshold: 30
  },
  {
    id: "legend_of_india",
    nameEn: "Legend of Duty Badge",
    nameHi: "भारत के लेजेंड बैज",
    virtueEn: "Unstoppable Patriot Legacy",
    virtueHi: "अजेय देशभक्त विरासत",
    icon: "💎",
    freedomFighter: "Freedom Movement Legend",
    quoteEn: "Your relentless discipline embodies the true spirit of Jai Hind!",
    quoteHi: "आपका निरंतर अनुशासन जय हिन्द की सच्ची भावना को दर्शाता है!",
    requirementEn: "Achieve 100-day streak legend status",
    requirementHi: "100-दिन स्ट्रिक लेजेंड स्थिति प्राप्त करें",
    type: "streak",
    threshold: 100
  }
];
